spring:
  mvc:
    servlet:
      path: /saturi-api
  datasource:
    url: jdbc:mysql://localhost:3306/saturi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: gkwo7108@gmail.com
    password: nqubrrxufkoexsgy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 50000
    auth-code-expiration-millis: 1800000
  jpa:
    hibernate:
      ddl-auto: create # 또는 필요에 따라 create, create-drop, validate로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # fetch join 후 지연로딩하는 entity을 in 절로 미리 영속성 컨텍스트에 저장

  # 선택사항: Hibernate 통계 정보 활성화
  # hibernate:
  #   generate_statistics: true

  jwt:
    salt: "ssafy-screte-key-20240719-ssafy-screte-key-20240719-ssafy-screte-key-20240719"
    access-token:
      expiretime: 3600000
      # expiretime: 20000
    refresh-token:
      expiretime: 2592000000
      # expiretime: 40000

  data:
    redis:
      host: localhost
      port: 6379

# 로그 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

social:
  client:
    kakao:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client-id: ce44932597263b3c038f3e226f3c3328
      redirect-uri: http://localhost:3000/user/auth/login/kakao
      client-secret: VGCitmfgTmn+t2ou+zVxu6OA7TYNSAApWRexee/pjXA=
    naver:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client_id: BUvsmsuF11bb6Ac_YdEh
      redirect-uri: http://localhost:3000/user/auth/login/naver
      client_secret: agzrMxlQfB

file:
  dir: C:\SSAFY\filetest\